apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 7233
      protocol: TCP
      targetPort: 7233
  selector:
    app: temporal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: default
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/admin-tools:latest
          command: ["bash", "-c"]
          args:
            - |
              export GODEBUG=http2debug=2
              temporal server start-dev --namespace v2 --ip 0.0.0.0
          ports:
            - containerPort: 7233
          livenessProbe:
            tcpSocket:
              port: 7233
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: default
  labels:
    app: temporal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: temporal-worker
    spec:
      containers:
      - name: worker
        image: "public.ecr.aws/i4h1y2p3/temporal/hello-world-worker:1.0.0"
        imagePullPolicy: Always
        env:
          - name: GODEBUG
            value: http2debug=2
          - name: TEMPORAL_CLIENT_HOSTPORT
            value: temporal.default.svc.cluster.local:7233
